"""
AtlasOS SQLAlchemy Base Model & Mixins.

Defines the declarative base class and reusable mixins for all ORM models.

Design decisions:
  - DeclarativeBase (SQLAlchemy 2.x): Replaces the legacy declarative_base()
    function. Provides better type inference and IDE support.
  - type_annotation_map: Maps Python types to SQLAlchemy column types globally.
    This eliminates redundant type specifications in individual models.
  - Mixins over inheritance: UUIDPrimaryKeyMixin, TimestampMixin, and
    TenantScopedMixin are mixins (not base classes) because:
    1. Not all tables need all three (e.g., audit_log has no updated_at).
    2. Mixins compose cleanly without diamond inheritance issues.
    3. Each mixin has a single responsibility (SOLID).

UUID primary keys:
  Server-generated via PostgreSQL's uuid_generate_v4(). This is preferred over
  client-side generation because it guarantees uniqueness within the database
  transaction, even under concurrent inserts from multiple application instances.

Timestamps:
  TIMESTAMPTZ (timezone-aware) ensures consistent time representation across
  time zones. server_default=func.now() generates timestamps at the database
  level, making them independent of application server clock skew.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any

import sqlalchemy as sa
from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


# Naming convention for database constraints.
# This ensures Alembic can autogenerate meaningful migration names and
# enables predictable constraint names for debugging and manual SQL.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """
    Declarative base for all AtlasOS SQLAlchemy models.

    Provides:
      - Global type annotation mapping (Python types → SA column types).
      - Consistent metadata naming convention for all constraints.
    """

    metadata = MetaData(naming_convention=NAMING_CONVENTION)

    type_annotation_map = {
        uuid.UUID: sa.Uuid,
        datetime: sa.DateTime(timezone=True),
        dict[str, Any]: sa.JSON,
    }


class UUIDPrimaryKeyMixin:
    """
    Mixin providing a UUID primary key column.

    Uses PostgreSQL's uuid_generate_v4() for server-side generation.
    This ensures IDs are generated atomically within the database
    transaction, preventing duplicates under concurrent inserts.
    """

    id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid,
        primary_key=True,
        server_default=sa.text("uuid_generate_v4()"),
        default=uuid.uuid4,
        doc="Unique identifier. Server-generated UUID v4.",
    )


class TimestampMixin:
    """
    Mixin providing created_at and updated_at timestamp columns.

    Both columns use TIMESTAMPTZ (timezone-aware). created_at is set once
    at insert time. updated_at is updated automatically by a PostgreSQL
    trigger (defined in the Alembic migration) on every UPDATE.

    The server_default ensures timestamps are generated by the database,
    not the application server, avoiding clock skew issues in distributed
    deployments.
    """

    created_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        doc="Timestamp when the record was created.",
    )

    updated_at: Mapped[datetime] = mapped_column(
        sa.DateTime(timezone=True),
        nullable=False,
        server_default=sa.func.now(),
        onupdate=sa.func.now(),
        doc="Timestamp when the record was last updated. Auto-updated by DB trigger.",
    )


class TenantScopedMixin:
    """
    Mixin for tables that are scoped to a specific tenant.

    Adds a tenant_id foreign key column referencing tenants.id with
    ON DELETE CASCADE. This column is used by PostgreSQL Row-Level
    Security (RLS) policies to enforce tenant isolation at the
    database level.

    Every query on a tenant-scoped table is automatically filtered
    by the RLS policy checking:
        tenant_id = current_setting('app.current_tenant_id')::uuid
    """

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        sa.Uuid,
        sa.ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Foreign key to the owning tenant. Used by RLS for isolation.",
    )
